### ISSUE TITLE
Notify on specific wormhole systems doesn't work

### ISSUE THREAD

**Issue by mcelrath** [Ionaru/TheraBot#23]
**Short description**
e.g. 
```/notify when J174618```
causes therabot to go into lala land "TheraBot is thinking..." and doesn't return.

Notifying on wormhole constellations does seem to work, however, but this is useless since w-space constellations are not connected.

**Expected behavior**
Notify when Thera connects to the specified wormhole system.

**Comment by Ionaru** [comment]
I'll need to do some more updates before deployment, but the fix should be live soon. :)
