### ISSUE TITLE
EVE-Scout API Updated to v2 - v1 No Longer Available

### ISSUE THREAD

**Issue by kibawulf** [Ionaru/TheraBot#24]
**Short description**
EVE-Scout has [updated its API as well as their website](https://signalcartel.org/new-eve-scout-thera-turnur-scanning-website-api) in general with some new features and seems to have decommissioned the original API located previously at:
https://www.eve-scout.com/api/wormholes

**Additional information**
The JSON API response has changed in at least naming conventions and some structure from the previous version, rendering the bot non-functional in its current state, even if the URL is updated. The URL below contains an updated schema sample of the new responses that appear most equivalent to the previous endpoint:
https://api.eve-scout.com/ui/#get-/v2/public/signatures

**Comment by Ionaru** [comment]
Thank you for the detailed analysis! I'll see what I can do with the new API.
If it provides the same information, then it should be easy to switch over.

**Comment by Kyoia** [comment]
I reworked the eve-scout.service.ts interfaces to try to get them to work with the new API. Check out my fork in the eve-scout-api-update branch if you're interested, I'm not very good with typescript so you probably don't want to use my other code. I added json response examples for the new eve-scout API's in __mock__ as well.  Thanks for your continued support on this project, it's incredibly useful!

**Comment by Ionaru** [comment]
The new API has been implemented! 😁
