### ISSUE TITLE
Double pings

### ISSUE THREAD

**Issue by mckernanin** [Ionaru/TheraBot#5]
**Short description**
I frequently get duplicate pings to discord for the same thera hole.

**To Reproduce**
1. Hook up to discord & setup feed

**Expected behavior**
I expect to see a single ping each time a new hole is scouted

**Screenshots**
![image](https://user-images.githubusercontent.com/6300047/83997427-978c8000-a91b-11ea-816e-e7b486de7a95.png)

**Comment by Ionaru** [comment]
Thank you for your report, I'll look into it
